# Generated by Django 3.2.20 on 2023-08-06 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
    ]
