# Generated by Django 3.2.20 on 2023-08-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_appointment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_slot', models.CharField(max_length=100)),
            ],
        ),
    ]
